services:
  sdm-reader:
    build: .
    container_name: sdm-modbus-reader
    restart: unless-stopped

    # Device access for serial port
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    # Privileged mode for serial port access (alternative to devices)
    # privileged: true

    # Ports
    ports:
      - "8000:8000"  # Web UI

    # Environment variables (optional - can use command args instead)
    environment:
      - TZ=Europe/Brussels

    # Command with all configuration (use array format for proper quoting)
    command:
      - python
      - -m
      - sdm_modbus_reader.sdm_modbus_reader
      - --device
      - "SDM630:100:Main Panel"
      - --device
      - "SDM120:101:Pv Inverter"
      - --device
      - "SDM120:102:Network"
      - --device
      - "SDM120:103:small oven"
      - --device
      - "SDM120:104:big oven"
      - --device
      - SDM120:105:heatpump
      - --device
      - SDM120:106:bikes
      - --serial-port
      - /dev/ttyUSB0
      - --baudrate
      - "9600"
      - --mqtt-broker
      - 192.168.1.5
      - --mqtt-port
      - "1883"
      - --mqtt-topic-prefix
      - klskmp/metering/sdm
      - --poll-interval
      - "10"

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network
    network_mode: bridge

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/meters"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s